name: gym_in
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^1.0.1
  firebase_auth: ^3.1.1
  firebase_analytics: ^8.3.4
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  hooks_riverpod: ^0.14.0+4
  image_cropper: ^1.4.1
  image_picker: ^0.8.3+2
  like_button: ^2.0.2
  material_floating_search_bar: ^0.3.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  qr_flutter: ^4.0.0
  razorpay_flutter: ^1.2.7
  reviews_slider: ^2.0.0
  shared_preferences: ^2.0.9
  dotted_line: ^3.1.0
  url_launcher:
  pedometer: ^3.0.0
  sensors_plus: ^1.2.1
  activity_recognition_flutter: ^4.0.5+1
  permission_handler: ^8.3.0
  path_provider: ^2.0.6
  barcode_scan2: ^4.1.4
  health: ^3.2.1
  percent_indicator: ^3.4.0
  syncfusion_flutter_datepicker: ^19.2.55
  table_calendar: ^3.0.2
  stop_watch_timer: ^1.3.1

dev_dependencies:
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  image: assets/img/splashlogo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/google-icon 1.png
    - assets/Burger-menu.png
    - assets/BurgermenudarkTheme.png
    - assets/post-image.jpg
    - assets/video_page_assets/AbsOverlay.png
    - assets/video_page_assets/BicepsOverlay.png
    - assets/video_page_assets/BodyBuilder.png
    - assets/video_page_assets/ChestOverlay.png
    - assets/home-page-heading.png
    - assets/g12.png
    - assets/img/splashlogo.png
    - assets/img/instagram.png
    - assets/img/animation_1.gif
    - assets/img/animation_50.gif
    - assets/img/start_50.gif
    - assets/img/error_50.gif

  fonts:
    - family: YellowTail
      fonts:
        - asset: fonts/YellowTail/Yellowtail-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
