name: gym_in
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0
  chewie: ^1.2.2

  cupertino_icons: ^1.0.3

  curved_navigation_bar: ^1.0.1

  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  font_awesome_flutter: ^9.1.0

  firebase_storage: ^10.0.3
  google_fonts: ^2.1.0
  like_button: ^2.0.2
  material_floating_search_bar: ^0.3.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  table_calendar: ^3.0.2
  video_player: ^2.1.12
  syncfusion_flutter_datepicker: ^19.2.55
  image_picker: ^0.8.3+2
  image_cropper: ^1.2.1
  razorpay_flutter: ^1.2.7
  pedometer: ^3.0.0
  percent_indicator: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:

flutter_native_splash:
  color: "#000000"
  image: assets/img/splashlogo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/google-icon 1.png
    - assets/Burger-menu.png
    - assets/post-image.jpg
    - assets/video_page_assets/AbsOverlay.png
    - assets/video_page_assets/BicepsOverlay.png
    - assets/video_page_assets/BodyBuilder.png
    - assets/video_page_assets/ChestOverlay.png
    - assets/home-page-heading.png
    - assets/g12.png
    - assets/img/splashlogo.png

  fonts:
    - family: YellowTail
      fonts:
        - asset: fonts/YellowTail/Yellowtail-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
